version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 16
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build --prod
  post_build:
    commands:
      - echo build process finished, we should upload to S3 now
      - ls 
      - cd dist/
      - ls -la
    #   - aws s3 sync . s3://www.pixelplay.app --delete
      - aws cloudfront create-invalidation --distribution-id=myid--paths '/*
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes